---
title: "Assessment #1: Data Audit Marking Rubric"
author: "Jon Reades"
date: "9/9/2022"
toc: false
number-sections: true
colorlinks: true
format:
  pdf:
    include-in-header:
      text: |
        \addtokomafont{disposition}{\rmfamily}
        \KOMAoption{fontsize}{11pt}
    #documentclass: report
    mainfont: "Spectral"
    papersize: a4
    geometry:
      - top=25mm
      - left=40mm
      - right=30mm
      - bottom=25mm
      - heightrounded
---

## Key Facts

- Deadline: {{< var assess.group-date >}}
- Weighting: 30% of module grade.
- Format: PDF submitted to Moodle. See [online guidance](https://jreades.github.io/fsds/assessments/audit.html) for details.

## Marking

Marks will be assigned using the following scale:

- **Weak**: Little or no argument or response presented; it is, at best, a gesture towards a critical engagement with the substance of the assessment. There is little or no evidence of doing the assigned readings.
- **Fair**: A sound argument or response; it demonstrates a basic level of critical engagement with the substance of the assessment. There is evidence of completing the assigned readings, but not of the deeper integration that comes from reflection. 
- **Excellent**: An outstanding argument or response; it engages critically and reflectively with the substance of the assessment. Not only is there evidence of the completion of the assigned readings, there is clear evidence of deeper integration through reflection.

|   | Question | Points | Word Count | Weak | Fair | Excellent |
|:--|:--------------------------|---:|------:|----:|----:|------:|
| 1 | Who collected the data? | 2 | 25 | 0 | 1-2 | N/A |
| 2 | Why did they collect it? | 4 | 50 | 0-1 | 2-4 | N/A |
| 3 | How was it collected? | 7 | 75 | 0-3 | 4-7 | N/A |
| 4 | What useful information does it contain? | 12 | 100 | 0-3 | 4-8 | 9-12 |
| 5 | To what extent is the data 'complete'? | 25 | 200 | 0-7 | 8-17 | 18-25 |
| 6 | What kinds of analysis would this support? | 15 | 200 | 0-5 | 6-10 | 11-15 |
| 7 | Which of these are *ethical*? | 35 | 350 | 0-10 | 11-24 | 25-35 |

*Note*: the word counts provided are indicative.
