---
title: "Assessment #2: Reproducible Analysis"
author: "Jon Reades"
date: "9/9/2023"
toc: false
number-sections: true
colorlinks: true
format:
  pdf:
    include-in-header:
      text: |
        \addtokomafont{disposition}{\rmfamily}
        \KOMAoption{fontsize}{11pt}
    #documentclass: report
    mainfont: "Spectral"
    papersize: a4
    geometry:
      - top=25mm
      - left=40mm
      - right=30mm
      - bottom=25mm
      - heightrounded
---

## Key Facts

- Deadline: {{< var assess.group-date >}}
- Weighting: {{< var assess.group-weight >}} of module grade (Reproducibility: {{< var assess.group-code-weight >}}; Content: {{< var assess.group-writing-weight >}}).
- Format: PDF and QMD (`.qmd` file) submitted to Moodle. See [online guidance](https://jreades.github.io/fsds/assessments/group.html) for details.

## Overview

The marking scheme for this submission has two parts:

1. The *Content* ({{< var assess.group-writing-weight >}} of total mark for this submission) will be assessed as an essay incorporating analytical elements; however, please note that a great deal of consideration will be given to the language, presentation, and content of the submission as befits a data-led briefing for a busy politician (the Mayor of London) and their policy-makers.
2. The *Reproducibility* ({{< var assess.group-code-weight >}} of total mark for this submission) will be assessed on the basis of how well it runs (its portability and robustness) and the quality of code (its efficiency and legibility).

The evaluation criteria span the skillset expected of a practicing analyst or data scientist: it is *not* just about writing code, but about selecting, developing, and communicating evidence with your ‘end user’ in mind, as well as demonstrating an understanding of how to give others within your organisation or team confidence in the results that you present.

The [models](https://jreades.github.io/fsds/assessments/models.html) provided should assist in determining whether you will do well in this area.

## Rubric

### Policy Briefing 

#### Question and Framing (20% of total mark)

This aspect is focussed on your ability to select and frame a research question or problem that is relevant to a specified audience.

| Guidance                                                     |               Grade |
| :----------------------------------------------------------- | ------------------: |
| The research problem has been well-developed and -framed for the specified audience. There is a broad range of background research entailing the use of diverse sources to produce a convincing framing of the topic. The briefing is clearly of compelling interest to the audience. | Distinction (>=70%) |
|                                                              |                     |
| The research problem has been developed for the specified audience. There is a range of background research used to produce a relevant framing of the topic. The briefing is clearly of interest to the audience, but makes some assumptions that suggest more limited reasoning about the audience. |      Merit (60–69%) |
|                                                              |                     |
| The research problem is of limited interest to the specified audience. There is a limited range of background research used to support the framing of the topic. Parts of the briefing are demonstrably of interest to the audience but this is only weakly-communicated or largely implicit. |       Pass (50-59%) |
|                                                              |                     |
| The research problem is not obviously of interest to the specified audience. There is a very limited range of background research used to support the framing of the topic. Few, if any, efforts are mode to make the briefing relevant to the audience, and the overall framing is weak and/or illogical. |         Fail (<50%) |

#### Analysis & Interpretation (30% of total mark)

This aspect is focussed on your ability to choose and employ the analytical tools covered in this and other modules (you are free to draw on knowledge developed in *Quantitative Methods* and *GIS*) to support your investigation of the research question.

| Evaluation                                                   |               Grade |
| :----------------------------------------------------------- | ------------------: |
| The analysis is excellent and entirely appropriate to the problem. It demonstrates a comprehensive technical understanding of how to select and deploy technical and statistical approaches in support of an analysis. Interpretations of results are very well constructed, clear and focused in relation to the research problem/framing. Maps, figures, and tables are excellent additions to the text and all work together to communicate effectively with the specified audience. | Distinction (>=70%) |
|                                                              |                     |
| The analysis is good and largely appropriate to the problem. It demonstrates a sound technical understanding of how to select and deploy technical and statistical approaches in support of an analysis, but with some opportunities for additional learning. Interpretations of results are logical and contain a well constructed discussion with linkage to the research problem. Maps, figures, and tables are appropriate, but could be improved upon or may contain minor errors. |      Merit (60–69%) |
|                                                              |                     |
| The analysis is relevant to the problem but lacks focus and/or clarity. It demonstrates sound understanding of individual technical and statistical approaches, but those selected may not be the most relevant to the research problem or could be better-specified. Interpretations of results are largely correct but need to be better-connected to the research problem. Maps, figures, and tables are adequate but more appropriate visualisations could have been implemented or may containt multiple errors that detract from their usefulness. |       Pass (50-59%) |
|                                                              |                     |
| The analysis does not address the problem effectively and demonstrates that the material covered in class has not been understood. It demonstrates limited  understanding of individual technical and statistical approaches, and those selected may not address the research problem or may be incorrectly-specified. Interpretations of results may not be correct or may not have a bearing on the research problem. Maps, figures, and tables are of poor quality and do not aid understanding in any way. |         Fail (<50%) |

#### Structure and Presentation (10% of total mark)

This aspect focusses on the attention you’ve given to communicating your results in a manner that is appropriate to the target audience.

| Guidance                                            |                    Grade |
| :----------------------------------------------------------- | -----------------------: |
| The briefing demonstrates an excellent awareness of its audience, and excellently balances the elements of a model data-led briefing. The linkage between sections is obvious and there is a strong narrative throughout. Tables, figures, and other elements are produced at a very high level with attention to details of content, colour, layout, and related aspects. | Distinction (>=70%) |
|  |  |
| The briefing demonstrates a good awareness of its audience, and there is a clear and logical structure to the data-led briefing. Attempts to link sections as part of an overall narrative are evident, but could be improved by further reflection about the audience and topic. Tables, figures, and other elements show some attention to details of content, colour, layout, and related aspects. | Merit (60–69%) |
|  |  |
| The report has an obvious structure but demonstrates a limited awareness of its audience. Connections between sections are weakly-articulated and the overall narrative is lost. Tables, figures, and other elements are of high quality but show little attention to detail. | Pass (50-59%) |
|  |  |
| The report is weakly structured and demonstrates a very limited awareness of its audience. There is no obvious linkage between sections and little narrative throughout. Tables, figures, and other elements are of poor quality and are difficult to read. | Fail (<50%) |

### Reproducible Analysis

#### Reproducibility (20% of total mark)

This aspect focusses on the attention you’ve given to ensuring that your analysis can be run on another system in two ways: 1) without changes being necessary to the code; and 2) with useful guidance being offered in terms of what to do if ‘things go wrong’. So this requires thinking about both ‘portability’ and how to ensure that a user can recover from a predictable failure.

| Evaluation                                                   |                    Grade |
| :----------------------------------------------------------- | -----------------------: |
| Your workbook runs without errors and obvious consideration has been given to ways that your code might fail on another system as well as the processes that could mitigate this. Documentation/comments neatly balance concision with readability. | Distinction(>=70%) |
|  |  |
| Your workbook runs without errors and there is some consideration of ways that your code might fail on another system as well as the processes that could mitigate this. Documentation/comments are generally good but may be uneven or excessive. |      Merit (60–69%) |
|  |  |
| Your workbook runs with minor errors (e.g. a path variable or missed library import from the SDS Docker image) that are quickly and easily resolved. Documentation/comments may be largely missing or gnomic when present. |       Pass (50-59%) |
|  |  |
| Your workbook does not run without significant edits to the code, such as installing a missing library or a failed download. Documentation/comments are minimal or incomprehensible. |         Fail (<50%) |

If you have, for instance, a NLP analysis that would take hours to run then it is acceptable to provide a partially-processed data file (i.e. at the point where the time-consuming analysis is complete) and to ‘comment out’ the cells that generated this data, but you *must* include the code used to generate this data.

#### Quality (20% of total mark)

This aspect focusses on the attention you’ve given to creating an analysis that is intelligible and well-presented such that another user doesn’t just ‘run the code’ but actually understands and has confidence in the how and why of what you’ve done. This is about making maximal use of the tools at your disposal such that the code is efficient, even elegant, and the outputs are clear and legible.

| Evaluation                                                   |                     Grade |
| :----------------------------------------------------------- | ------------------------: |
| Another data scientist could understand and use your code with minimal effort and would appreciate the overall ‘style’ of the notebook. The code is well-organised, with each step of the analysis undertaken in a logical, structured way with little or no duplication or confusion. The code is highly-efficient, demonstrating a comprehensive understanding of the best practices taught on the course (e.g. intelligent creation of functions where appropriate, iterations to work efficiently with data/loops, and/or includes advanced programming techniques). Clever and creative use of the packages taught on the course. | Distinction (>=70%) |
|  |  |
| Another data scientist could understand and use your code with some effort but would find the overall ‘style’ of the notebook to be both clear and consistent. The code is generally well-organised, with most steps of the analysis undertaken in a logical, structured way with minimal duplication or confusion.  The code is  reasonably efficient, demonstrating a good understanding of the best practices taught on the course (e.g. intelligent creation of functions where appropriate, iterations to work efficiently with data/loops, and/or includes advanced programming techniques). Appropriate use of the packages taught on the course. |      Merit (60–69%) |
|  |  |
| Another data scientist could understand and use your code only with significant effort and would find the overall ‘style’ of the notebook to be both unclear and inconsistent. The code is could be better-organised, with greater structure leading to reduced duplication or confusion.  The code could be more efficient, suggesting a fairly basic understanding of the best practices taught on the course (e.g. intelligent creation of functions where appropriate, iterations to work efficiently with data/loops, and/or includes advanced programming techniques). Weak use of the packages taught on the course. |        Pass (50-59%) |
|  |  |
| Another data scientist could not understand and use your code, would not be inclined to invest the effort in doing so as they would find the overall ‘style’ of the notebook to be fundamentally unclear and confusingly inconsistent. The code is disorganised, with a substantial amount of duplication and confusion.  The code is inefficient, suggesting little or no understanding of the best practices taught on the course (e.g. intelligent creation of functions where appropriate, iterations to work efficiently with data/loops, and/or includes advanced programming techniques). Fundamental errors are made in the use of the packages taught on the course. |          Fail (<50%) |
